In [4]:
import numpy as np

## numpy 를 사용해 
## 아래 내용이 나오도록 근데 적기 귀찮음

In [3]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3

In [5]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4

In [7]:
cut = np.ones((10))
cut[0:] = 5
cut

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5

In [17]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6

In [18]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7

In [26]:
my = [0,1,2],[3,4,5],[6,7,8]
np.array(my)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8

In [28]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9

In [231]:
np.random.rand(1)

array([0.87765528])

10 와 진 짜  모 르 겠 다.

In [324]:
np.random.randn(5,5)

array([[ 1.04549905,  1.20008946, -0.86016235,  0.41534366, -2.35703459],
       [-0.91477261, -1.36451768,  1.0456418 ,  1.81665389,  0.47419273],
       [ 0.15004764, -3.10056197,  0.58837671, -0.4932831 , -0.06856491],
       [-0.40527019,  1.39182468,  1.21185168, -0.92286863,  1.12334151],
       [-1.63667997, -0.05302088, -2.18135487,  0.08043476, -1.27572173]])

11

In [333]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12

In [131]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13

In [151]:
mat = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]))
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

14

In [152]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

15

In [337]:
mat[3][4]

20

17

In [154]:
mat[4]

array([21, 22, 23, 24, 25])

18

In [155]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

16

In [183]:
mat[0:,:2][:3,1:]

array([[ 2],
       [ 7],
       [12]])

19

In [321]:
mat[4][4]*13

325

In [338]:
mat.sum()

325